# https://docs.travis-ci.com/user/build-config-imports/
version: ~> 1.0

import:
  - silverstripe/silverstripe-travis-shared:config/provision/standard-jobs-behat.yml

env:
  global:
    - COMPOSER_ROOT_VERSION="2.3.x-dev"
    - BEHAT_SUITE="@subsites"
